baseurl = "https://ivc.bioinit.com"
RelativeURLs=true
CanonifyURLs=true
languageCode = "zh-cmn-Hans"	                  # html的lang属性值
DefaultContentLanguage = "zh-cmn-Hans"   	  # 默认内容语言用于选择i18n语言模板
title = "Steven Shen | 沈维燕"
theme = "hugo-ivy"
#googleAnalytics = "UA-112592341-1"
disqusShortname = "bioinit"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true                             # .WordCount works correctly for chinese
enableEmoji = true
footnotereturnlinkcontents = "↩"
MetaDataFormat = "yaml" 			  # format of a new post
enableGitInfo = false
publishDir = "docs"


[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "博客"
    url = "/blog/"
    weight = 3

[[menu.main]]
    name = "研究"
    url = "/research/"
    weight = 4

[[menu.main]]
    name = "读书"
    url = "/read/"
    weight = 5

[[menu.main]]
    name = "简历"
    url = "/resume/shenweiyan"
    weight = 6

[[menu.main]]
    name = "专栏"
    url = "/topic/"
    weight = 7

[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 8

[[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 9

[[menu.topic]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.topic]]
    name = "Galaxy"
    url = "/topic/galaxy/"
    weight = 2

[params]
    siteurl = "https://ivc.bioinit.com"
    description = ""
    disqusURL = "https://shenweiyan.github.io/home/"
    customJS = ["js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js", "js/external-link.js", "js/alt-title.js", "js/header-link.js", "js/dom-scripts.js"]
    githubContentURL = "https://github.com/shenweiyan/home/edit/master/content/"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsTheme = "github"
    dateFormat = "2019-01-01" # "2019-01-01, Mon, "

[params.footer]
    home = "<br/><br/>Powered by [Hugo](https://gohugo.io) and [Blogdown](https://bookdown.org/yihui/blogdown/) &copy; [Steven Shen](/) 2018 - 2019 <br/><br/>[<i class='far fa-envelope fa-1x'></i>](mailto:ishenweiyan@qq.com) &middot; [<i class='fab fa-github fa-1x'></i>](https://github.com/shenweiyan) &middot; [<i class='fab fa-stack-overflow fa-1x'></i>](https://stackoverflow.com/users/9701168/steven-shen)"

[params.author]
    en = "Steven Shen"
    cn = "沈维燕"

[params.logo.en]
    img = "https://apps-db.oss-cn-shenzhen.aliyuncs.com/logos/shenweiyan.png"
    url = "/"
    alt = "Steven Shen"
    tag = ""

[params.lang.edit]
    cn = "编辑"
[params.lang.license]
    cn = "版权"
[params.lang.subscribe]
    cn = "订阅"

[taxonomies]
    tag = "tags"
    series = "series"
    category = "categories"
